DROP DATABASE QLLKMT
GO
CREATE DATABASE QLLKMT
GO
USE QLLKMT
GO

---Tạo bảng nhân viên
CREATE TABLE NHANVIEN
(
	MANV CHAR(5) NOT NULL PRIMARY KEY,
	TENNV NVARCHAR(50), 
	NGSINH SMALLDATETIME,
	GIOITINH INT,
	DIACHI NVARCHAR(50),
	SDT VARCHAR(11),
	MALOAI CHAR(5)
)

---Tạo bảng phân loại nhân viên
CREATE TABLE PLNHANVIEN
(
	MALOAI CHAR(5) NOT NULL PRIMARY KEY,
	TENLOAI NVARCHAR(25),
)

---Tạo bảng sản phẩm
CREATE TABLE SANPHAM
(
	MASP CHAR(5) NOT NULL PRIMARY KEY,
	TENSP NVARCHAR(100), 
	TGBAOHANH int,
	SOLUONG int, 
	TRANGTHAI NVARCHAR(20),
	DONGIA MONEY,
	MALOAI CHAR(5),
	MANCC CHAR(5)
)

---Tạo bảng loại sản phẩm
CREATE TABLE LOAISP
(
	MALOAI CHAR(5) NOT NULL PRIMARY KEY,
	TENLOAI NVARCHAR(20)
)

---Tạo bảng nhà cung cấp
CREATE TABLE NHACUNGCAP
(
	MANCC CHAR(5) NOT NULL PRIMARY KEY,
	TENNCC NVARCHAR(50),
	SDT VARCHAR(11),
	DIACHI NVARCHAR(100)
)

---Tạo bảng hóa đơn nhập hàng
CREATE TABLE HDNHAPHANG
(
	MAHDNH CHAR(5) NOT NULL PRIMARY KEY,
	MANV CHAR(5),
	MANCC CHAR(5),
	NGAYNH SMALLDATETIME,
	TONGTIEN MONEY
)

---Tạo bảng chi tiết hóa đơn nhập hàng
CREATE TABLE CTHDNHAPHANG
(	
	MACTHDNH CHAR(5) NOT NULL PRIMARY KEY, 
	MAHDNH CHAR(5),
	MASP CHAR(5),
	SOLUONG INT,
	GIANHAP MONEY,
)

---Tạo bảng khách hàng
CREATE TABLE KHACHHANG
(
	MAKH CHAR(5) NOT NULL PRIMARY KEY,
	TENKH NVARCHAR(50),
	SDT VARCHAR(11)
)

---Tạo bảng hóa đơn bán hàng
CREATE TABLE HDBANHANG
(
	MAHDBH CHAR(5) NOT NULL PRIMARY KEY,
	MANV CHAR(5),
	MAKH CHAR(5),
	NGAYBH SMALLDATETIME,
	THANHTIEN MONEY
)

---Tạo bảng chi tiết hóa đơn bán hàng
CREATE TABLE CTHDBANHANG
(
	MACTHDBH CHAR(5) NOT NULL PRIMARY KEY, 
	MAHDBH CHAR(5),
	MASP CHAR(5),
	SOLUONG INT,
)

---Tạo khóa ngoại cho bảng nhân viên
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NV_PLNV FOREIGN KEY(MALOAI) REFERENCES PLNHANVIEN(MALOAI)

---Tạo khóa ngoại cho bảng chi tiết hóa đơn bán hàng
ALTER TABLE CTHDBANHANG ADD CONSTRAINT FK_CTHDBH_HDBH FOREIGN KEY(MAHDBH) REFERENCES HDBANHANG(MAHDBH)
ALTER TABLE CTHDBANHANG ADD CONSTRAINT FK_CTHDBH_SP FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)

---Tạo khóa ngoại cho bảng hoá đơn bán hàng
ALTER TABLE HDBANHANG ADD CONSTRAINT FK_HDBH_NV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE HDBANHANG ADD CONSTRAINT FK_HDBH_KH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)

---Tạo khóa ngoại cho bảng chi tiết hoá đơn nhập hàng
ALTER TABLE CTHDNHAPHANG ADD CONSTRAINT FK_CTHDNH_HDNH FOREIGN KEY(MAHDNH) REFERENCES HDNHAPHANG(MAHDNH)
ALTER TABLE CTHDNHAPHANG ADD CONSTRAINT FK_CTHDNH_SP FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)

---Tạo khóa ngoại cho bảng hoá đơn nhập hàng
ALTER TABLE HDNHAPHANG ADD CONSTRAINT FK_HDNH_NCC FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP(MANCC)
ALTER TABLE HDNHAPHANG ADD CONSTRAINT FK_HDNH_NV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)


---Tạo khóa ngoại cho bảng sản phẩm
ALTER TABLE SANPHAM ADD CONSTRAINT FK_SP_NCC FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP(MANCC)
ALTER TABLE SANPHAM ADD CONSTRAINT FK_SP_LSP FOREIGN KEY(MALOAI) REFERENCES LOAISP(MALOAI)