
INSERT INTO LOAISP VALUES ('ML001',N'LAPTOP');
INSERT INTO LOAISP VALUES ('ML002',N'MÀN HÌNH VI TÍNH');
INSERT INTO LOAISP VALUES ('ML003',N'BO MẠCH CHỦ');
INSERT INTO LOAISP VALUES ('ML004',N'CPU');
INSERT INTO LOAISP VALUES ('ML005',N'RAM');
INSERT INTO LOAISP VALUES ('ML006',N'Ổ CỨNG DI ĐỘNG');
INSERT INTO LOAISP VALUES ('ML007',N'Ổ CỨNG GẮN TRONG');
INSERT INTO LOAISP VALUES ('ML008',N'THẺ NHỚ');
INSERT INTO LOAISP VALUES ('ML009',N'USB');
INSERT INTO LOAISP VALUES ('ML010',N'NGUỒN MÁY TÍNH');
INSERT INTO LOAISP VALUES ('ML011',N'CASE');
INSERT INTO LOAISP VALUES ('ML012',N'CARD MÀN HÌNH');
INSERT INTO LOAISP VALUES ('ML013',N'BÀN PHÍM MÁY TÍNH');
INSERT INTO LOAISP VALUES ('ML014',N'CHUỘT MÁY TÍNH');
