--- Load Nhân viên
CREATE PROC	Nhanvien_Load
AS
BEGIN
	SELECT NV.MANV, NV.TENNV, NV.NGSINH,NV.GIOITINH,NV.DIACHI, NV.SDT,NV.MALOAI, PL.TENLOAI 
	FROM NHANVIEN NV join PLNHANVIEN PL on NV.MALOAI = PL.MALOAI
END

---Thêm nhân viên
GO
CREATE PROC	Nhanvien_Insert(
	@MANV CHAR(5),
	@TENNV NVARCHAR(50),
	@NGSINH SMALLDATETIME,
	@GIOITINH NVARCHAR(3),
	@DIACHI NVARCHAR(50),
	@SDT VARCHAR(11),
	@MALOAI CHAR(5)
)
AS
BEGIN
	INSERT INTO NHANVIEN VALUES (@MANV, @TENNV, @NGSINH, @GIOITINH, @DIACHI, @SDT, @MALOAI)
END

---Xóa nhân viên
GO
CREATE PROC	Nhanvien_Detele(
	@MANV CHAR(5)
)
AS
BEGIN
	DELETE FROM NHANVIEN WHERE MANV = @MANV
END

---Sửa nhân viên
GO
CREATE PROC	Nhanvien_Update(
	@MANV CHAR(5),
	@TENNV NVARCHAR(50),
	@NGSINH SMALLDATETIME,
	@GIOITINH NVARCHAR(3),
	@DIACHI NVARCHAR(50),
	@SDT VARCHAR(11),
	@MALOAI CHAR(5)
)
AS
BEGIN
	UPDATE NHANVIEN 
	SET TENNV = @TENNV, 
		NGSINH = @NGSINH, 
		GIOITINH = @GIOITINH, 
		DIACHI = @DIACHI,
		SDT = @SDT,
		MALOAI = @MALOAI
	WHERE MANV = @MANV
END



--- Tìm kiếm nhân viên theo tên hoặc theo số điện thoại (Full Text Search)
GO
CREATE PROC NhanVien_Search(
	@CHUOI NVARCHAR(50)
)
AS
BEGIN
	SELECT * 
	FROM NHANVIEN NV join PLNHANVIEN PL on NV.MALOAI = PL.MALOAI
	WHERE FREETEXT(TENNV, @CHUOI) OR SDT LIKE '%' + @CHUOI + '%' OR TENNV LIKE N'%' +@CHUOI+ '%'
END

go
--load ten NV
GO
CREATE PROC NhanVien_SelectTenNV
AS
BEGIN
	SELECT MANV ,TENNV 
	FROM NHANVIEN
END

--load ma NV
go
CREATE PROC NhanVien_SelectMaNV(
	@TENNV NVARCHAR(50)
)
AS
BEGIN
	SELECT MANV 
	FROM NHANVIEN
	WHERE TENNV = @TENNV 
END

--chon loai nhan vien
GO
CREATE PROC	PLNhanVien_SelectLoaiNV
AS
BEGIN
	SELECT * FROM PLNHANVIEN
END

--- Thêm hóa đơn bán hàng
GO 
CREATE PROC HDBanHang_Insert(
	@MAHDBH CHAR(5),
	@MANV CHAR(5),
	@MAKH CHAR(5),
	@NGAYBH SMALLDATETIME,
	@THANHTIEN MONEY
)
AS
BEGIN
	INSERT INTO HDBANHANG VALUES (@MAHDBH, @MANV, @MAKH, @NGAYBH, @THANHTIEN)
END

--- Sửa hóa đơn bán hàng
GO 
CREATE PROC HDBanHang_Update(
	@MAHDBH CHAR(5),
	@MANV CHAR(5),
	@MAKH CHAR(5),
	@NGAYBH SMALLDATETIME,
	@THANHTIEN MONEY
)
AS
BEGIN
	UPDATE HDBANHANG 
	SET
		MAKH = @MAKH,
		NGAYBH = @NGAYBH,
		THANHTIEN = @THANHTIEN
	WHERE MAHDBH = @MAHDBH
END

--- Thêm chi tiết hóa đơn bán hàng
GO 
CREATE PROC CTHDBanHang_Insert(
	@MACTHDBH CHAR(5),
	@MAHDBH CHAR(5),
	@MASP CHAR(5),
	@SOLUONG INT
)
AS
BEGIN
	INSERT INTO CTHDBANHANG VALUES (@MACTHDBH, @MAHDBH, @MASP, @SOLUONG)
END

--- Xóa chi tiết hóa đơn bán hàng
GO
CREATE PROC	CTHDBanHang_Delete(
	@MACTHDBH CHAR(5)
)
AS
BEGIN
	DELETE FROM CTHDBANHANG WHERE MACTHDBH = @MACTHDBH
END

--- Sửa chi tiết hóa đơn bán hàng
GO 
CREATE PROC CTHDBanHang_Update(
	@MACTHDBH CHAR(5),
	@MAHDBH CHAR(5),
	@MASP CHAR(5),
	@SOLUONG INT
)
AS
BEGIN
	UPDATE CTHDBANHANG 
	SET 
		MASP = @MASP,
		SOLUONG = @SOLUONG
	WHERE MACTHDBH = @MACTHDBH
END

--- Load các chi tiết hóa đơn bán hàng của một hóa đơn
GO 
CREATE PROC CTHDBanHang_Load(
	@MAHDBH CHAR(5)
)
AS
BEGIN
	SELECT CTHDBH.MASP, CTHDBH.MACTHDBH, SP.TENSP, CTHDBH.SOLUONG 
	FROM CTHDBANHANG CTHDBH join SANPHAM SP on CTHDBH.MASP = SP.MASP
	WHERE MAHDBH = @MAHDBH
END

---Load Top 1 MaKH
GO
CREATE PROC	Khachhang_LoadTop1
AS
BEGIN
	SELECT TOP(1) MAKH
	FROM KHACHHANG
	GROUP BY MAKH
	ORDER BY MAKH DESC
END

---Load TENKH va MAKH
GO
CREATE PROC	Khachhang_LoadMaTen
AS
BEGIN
	SELECT MAKH, TENKH
	FROM KHACHHANG
END

--Load DIACHI va SDT KH
GO
CREATE PROC	Khachhang_LoadThongtinKH
(
	@MAKH CHAR(5)
)
AS
BEGIN
	SELECT DIACHI,SDT
	FROM KHACHHANG
	WHERE MAKH = @MAKH
END

--- Thêm khach hang
GO 
CREATE PROC Khachhang_Insert(
	@MAKH CHAR(5),
	@TENKH NVARCHAR(50),
	@SDT VARCHAR(11),
	@DIACHI NVARCHAR(100)
)
AS
BEGIN
	INSERT INTO KHACHHANG VALUES (@MAKH, @TENKH, @SDT, @DIACHI)
END

---Update Khach hang
--- Thêm khach hang
GO 
CREATE PROC Khachhang_Update(
	@MAKH CHAR(5),
	@TENKH NVARCHAR(50),
	@SDT VARCHAR(11),
	@DIACHI NVARCHAR(100)
)
AS
BEGIN
	UPDATE KHACHHANG 
	SET 
		TENKH = @TENKH,
		SDT = @SDT,
		DIACHI = @DIACHI
	WHERE MAKH = @MAKH
END

--- Load ten sp
GO 
CREATE PROC Sanpham_Load
AS
BEGIN
	SELECT MASP, TENSP
	FROM SANPHAM
END

--- chọn top 1 hóa đơn bán
GO
CREATE PROC HDBanHang_LoadTop1
AS
BEGIN
	SELECT TOP(1) MAHDBH
	FROM HDBANHANG
	GROUP BY MAHDBH
	ORDER BY MAHDBH DESC
END

-- load don gia SP
GO
CREATE PROC Sanpham_LoadDongia(
	@MASP CHAR(5)
)
AS
BEGIN
	SELECT DONGIA
	FROM SANPHAM
	WHERE MASP = @MASP
END

--- chọn top 1 chi tiet hóa đơn bán
GO
CREATE PROC CTHDBH_LoadTop1
AS
BEGIN
	SELECT TOP(1) MACTHDBH
	FROM CTHDBANHANG
	GROUP BY MACTHDBH
	ORDER BY MACTHDBH DESC
END

go
CREATE PROC LoaiSanPham_SelectAll
AS
BEGIN
	SELECT * FROM LOAISP
END

GO
CREATE PROC NCC_SelectAll
AS
BEGIN
	SELECT * FROM NHACUNGCAP
END

GO
CREATE PROC SanPham_MASP_TOP1
AS
BEGIN
	SELECT TOP(1) SP.MASP 
	FROM SANPHAM AS SP
	ORDER BY SP.MASP desc
END


GO
--- Lấy mã loại trong bản sản phẩm
CREATE PROC LoaiSanPham_MaLoai
AS
BEGIN
	SELECT SP.MALOAI 
	FROM SANPHAM AS SP, LOAISP AS LSP
	WHERE SP.MALOAI = LSP.MALOAI
END

GO
CREATE PROC NhaCungCap_TOP
AS
BEGIN
	SELECT TOP(1) MANCC
	FROM NHACUNGCAP
	GROUP BY MANCC
	ORDER BY MANCC DESC
END


GO
--- Lấy tất cả nhà cung cấp ra.
CREATE PROC NhaCungCap_SelectAll
AS
BEGIN
	SELECT * FROM NHACUNGCAP 
END

--- Lấy tất cả hóa đươn nhập hàng ra
GO
CREATE PROC HoaDonNhap_SelectAll
AS
BEGIN 
	SELECT * FROM HDNHAPHANG
END

--- Load MAHDNH, TENNV, TENNCC, NGAYNH, TONGTIEN
GO
CREATE PROC HoaDonNhap_Load
AS
BEGIN 
	SELECT HDNH.MAHDNH, HDNH.MANV,NV.TENNV, HDNH.MANCC, NCC.TENNCC, HDNH.NGAYNH, HDNH.TONGTIEN
	FROM HDNHAPHANG AS HDNH, NHANVIEN AS NV, NHACUNGCAP AS NCC
	WHERE HDNH.MANV = NV.MANV AND HDNH.MANCC = NCC.MANCC
END

--- Insert hóa đơn nhập
GO
CREATE PROC HoaDonNhap_Insert(
	@MAHDNH CHAR(5),
	@MANV CHAR(5),
	@MANCC CHAR(5),
	@NGAYNH SMALLDATETIME,
	@TONGTIEN MONEY
)
AS
BEGIN
	INSERT INTO HDNHAPHANG(MAHDNH, MANV, MANCC, NGAYNH, TONGTIEN) 
	VALUES (@MAHDNH, @MANV, @MANCC, @NGAYNH, @TONGTIEN)
END


--- Delete hóa đơn nhập
GO
CREATE PROC HoaDonNhap_Delete(
	@MAHDNH CHAR(5)
)
AS
BEGIN
	DELETE FROM CTHDNHAPHANG WHERE MAHDNH = @MAHDNH
	DELETE FROM HDNHAPHANG WHERE MAHDNH = @MAHDNH
END


--- Load chi tiết hóa đơn nhập
GO
CREATE PROC CTHDNhap_Load(
	@MAHDNH CHAR(5)
)
AS
BEGIN
	SELECT CTHDNH.MACTHDNH, CTHDNH.MAHDNH,CTHDNH.MASP, SP.TENSP, CTHDNH.SOLUONG, CTHDNH.GIANHAP 
	FROM SANPHAM AS SP, CTHDNHAPHANG AS CTHDNH
	WHERE CTHDNH.MASP = SP.MASP AND CTHDNH.MAHDNH = @MAHDNH
END

--- Thêm chi tiết hóa đơn nhập
GO
CREATE PROC CTHDNhap_Insert(
	@MACTHDNH CHAR(5),
	@MAHDNH CHAR(5),
	@MASP CHAR(5),
	@SOLUONG INT,
	@GIANHAP MONEY
)
AS
BEGIN
	INSERT INTO CTHDNHAPHANG(MACTHDNH, MAHDNH, MASP, SOLUONG, GIANHAP) 
	VALUES (@MACTHDNH, @MAHDNH, @MASP, @SOLUONG, @GIANHAP)
END

GO
--- Lấy Mã nhân viên, Tên nhân viên
CREATE PROC NhanVien_Select_Element
AS
BEGIN
	SELECT MANV, TENNV
	FROM NHANVIEN
END

GO
--- Lay danh sach NCC theo 
CREATE PROC NhaCungCap_Select_Element
AS
BEGIN
	SELECT MANCC, TENNCC
	FROM NHACUNGCAP
END

GO
--- Delete chi tiết hóa đơn nhập
CREATE PROC CTHDNhap_Delete(
	@MACTHDNH CHAR(5)
)
AS
BEGIN
	DELETE FROM CTHDNHAPHANG WHERE MACTHDNH = @MACTHDNH
END

GO
--- DELETE CI HDNHAP 
CREATE PROC CTHDNhap_Delete_NOMACT(
	@MAHDNH CHAR(5),
	@MASP CHAR(5)
)
AS
BEGIN
	DELETE FROM CTHDNHAPHANG WHERE MAHDNH = @MAHDNH AND MASP = @MASP
END

GO
--- SEARCH 
--- UPADATE HD NHAP HANG
CREATE PROC HDNhapHang_Update(
	@MAHDNH CHAR(5),
	@MANV CHAR(5),
	@MANCC CHAR(5),
	@NGAYNHAP DATETIME,
	@TONGTT MONEY
)
AS
BEGIN
	UPDATE HDNHAPHANG
	SET MANV = @MANV, MANCC = @MANCC, NGAYNH= @NGAYNHAP, TONGTIEN = @TONGTT
	WHERE MAHDNH = @MAHDNH
END

GO
--- UPDATE CTHD NHAP HANG ---
CREATE PROC CTHD_Update2(
	@MACTHDN CHAR(5),
	@MASP CHAR(5),
	@SOLUONG INT,
	@GIANHAP MONEY
)
AS
BEGIN
	UPDATE CTHDNHAPHANG
	SET MASP= @MASP, SOLUONG= @SOLUONG, GIANHAP = @GIANHAP
	WHERE MACTHDNH = @MACTHDN
END

GO
--- LAY MA HDNHAP LON NHAT ---
CREATE PROC HDN_MAHDN_TOP1
AS
BEGIN
	SELECT TOP 1 MAHDNH
	FROM HDNHAPHANG
	ORDER BY MAHDNH DESC
END

GO
--- --- LAY MA CTHDNHAP LON NHAT ---
CREATE PROC HDN_CTHDN_TOP1
AS
BEGIN
	SELECT TOP 1 MACTHDNH
	FROM CTHDNHAPHANG
	ORDER BY MACTHDNH DESC
END

GO
--- LOAD SP ---
CREATE PROC LOAD_SANPHAM_ELEMENT
AS
BEGIN
	SELECT MASP, TENSP
	FROM SANPHAM
END

GO
--- HOADONNHAPHANG _ WITH MAHD ---
CREATE PROC HDNH_WITHMAHD
( @MAHDNH CHAR(5)
)
AS
BEGIN
	SELECT HDNH.MAHDNH, HDNH.MANV,NV.TENNV, HDNH.MANCC, NCC.TENNCC, HDNH.NGAYNH, HDNH.TONGTIEN
	FROM HDNHAPHANG AS HDNH, NHANVIEN AS NV, NHACUNGCAP AS NCC
	WHERE HDNH.MANV = NV.MANV AND HDNH.MANCC = NCC.MANCC AND MAHDNH = @MAHDNH
END


--- Load lên tên sản phẩm ( Full-Text Search)
GO
CREATE PROC SANPHAM_SEARCH(
	@TENSP NVARCHAR(100)
)
AS
BEGIN
	SELECT *
	FROM SANPHAM
	WHERE FREETEXT(TENSP, @TENSP) OR TENSP LIKE '%' + @TENSP + '%'
END

--- Tính tổng tiền sản phẩm ở bảng HDBANHANG
GO
CREATE PROC HDBH_SumMoney(
	@MAHDBH CHAR(5)
)
AS
BEGIN
	SELECT SUM(CTHDBH.SOLUONG * SP.DONGIA) AS TONGTIENBH
	FROM CTHDBANHANG AS CTHDBH, SANPHAM AS SP
	WHERE CTHDBH.MASP = SP.MASP AND CTHDBH.MAHDBH = @MAHDBH
END

--- UPDATE Thành tiền của HDBANHANG
GO
CREATE PROC HDBANHANG_Update_ThanhTien(
	@THANHTIEN INT,
	@MAHDBH CHAR(5)
)
AS
BEGIN
	UPDATE HDBANHANG
	SET THANHTIEN = @THANHTIEN
	WHERE MAHDBH = @MAHDBH
END

--- Lấy thông tin đăng nhập
GO
CREATE PROC PLNhanVien_Check(
	@USERNAME VARCHAR(20),
	@PASSWORD VARCHAR(15)
)
AS
BEGIN
	SELECT * 
	FROM PLNHANVIEN
	WHERE TENDANGNHAP = @USERNAME AND MATKHAU = @PASSWORD
END

--- Kiểm tra MASP có tồn tại 1 trong 2 bảng CTHDBANHANG, CTHDNHAPHANG
GO
CREATE PROC SANPHAM_CHECK(
	@MASP CHAR(5)
)
AS
BEGIN
	SELECT SP.MASP 
	FROM SANPHAM AS SP
	WHERE MASP = @MASP AND MASP IN(
		SELECT DISTINCT SP.MASP 
		FROM SANPHAM AS SP 
		INNER JOIN CTHDBANHANG AS CTHDBH ON CTHDBH.MASP = SP.MASP
		UNION
		SELECT DISTINCT SP.MASP 
		FROM SANPHAM AS SP 
		INNER JOIN CTHDNHAPHANG AS CTHDNH ON CTHDNH.MASP = SP.MASP
	)
END

--- Load thông tin tài khoản và thông tin nhân viên lên
GO
CREATE PROC TKNhanVien_NhanVien_Load
AS
BEGIN
	SELECT TKNV.MATK, NV.MANV, NV.TENNV, TKNV.TENDANGNHAP, TKNV.MATKHAU, PLNV.TENLOAI
	FROM NHANVIEN AS NV FULL OUTER JOIN TKNHANVIEN AS TKNV ON TKNV.MANV = NV.MANV
	INNER JOIN PLNHANVIEN AS PLNV ON NV.MALOAI = PLNV.MALOAI
END

--- Select top 1 MATK DESC
GO
CREATE PROC TKNhanVien_Top1
AS
BEGIN
	SELECT TOP(1) MATK
	FROM TKNHANVIEN
	WHERE EXISTS (
		SELECT TKNV.MATK, NV.MANV, NV.TENNV, TKNV.TENDANGNHAP, TKNV.MATKHAU, PLNV.TENLOAI
		FROM NHANVIEN AS NV FULL OUTER JOIN TKNHANVIEN AS TKNV ON TKNV.MANV = NV.MANV
		INNER JOIN PLNHANVIEN AS PLNV ON NV.MALOAI = PLNV.MALOAI
	)
	ORDER BY MATK DESC
END

--- Thêm tài khoản cho nhân viên
GO
CREATE PROC TKNhanVien_Insert(
	@MATK CHAR(5),
	@MANV CHAR(5),
	@USERNAME VARCHAR(20),
	@PASSWORD VARCHAR(15)
)
AS
BEGIN
	INSERT INTO TKNHANVIEN
	VALUES(@MATK, @MANV, @USERNAME, @PASSWORD)
END

--- Xóa tài khoản nhân viên
GO
CREATE PROC TKNhanVien_Delete(
	@MATK CHAR(5)
)
AS
BEGIN
	DELETE 
	FROM TKNHANVIEN 
	WHERE MATK = @MATK
END

--- Sửa tài khoản nhân viên
GO
CREATE PROC TKNhanVien_Update(
	@MATK CHAR(5),
	@USERNAME VARCHAR(20),
	@PASSWORD VARCHAR(15)
)
AS
BEGIN
	UPDATE TKNHANVIEN
	SET TENDANGNHAP = @USERNAME,
		MATKHAU = @PASSWORD
	WHERE MATK = @MATK
END


--- Check username, password
GO
CREATE PROC TKNhanVien_Check(
	@USERNAME VARCHAR(20),
	@PASSWORD VARCHAR(15)
)
AS
BEGIN
	SELECT TKNV.MATK, NV.MANV, NV.TENNV, TKNV.TENDANGNHAP, TKNV.MATKHAU, PLNV.TENLOAI
	FROM NHANVIEN AS NV FULL OUTER JOIN TKNHANVIEN AS TKNV ON TKNV.MANV = NV.MANV
	INNER JOIN PLNHANVIEN AS PLNV ON NV.MALOAI = PLNV.MALOAI
	WHERE TKNV.TENDANGNHAP = @USERNAME AND TKNV.MATKHAU = @PASSWORD
END

--- Tru so luong cua 1 san pham
GO
CREATE PROC SANPHAM_CapnhatSL(
	@SOLUONG INT,
	@MASP CHAR(5)
)
AS
BEGIN
	UPDATE SANPHAM
	SET SOLUONG = @SOLUONG
	WHERE MASP = @MASP
END

--- lay so luong cua 1 san pham
GO
CREATE PROC SANPHAM_LaySL(
	@MASP CHAR(5)
)
AS
BEGIN
	SELECT SOLUONG
	FROM SANPHAM
	WHERE MASP = @MASP
END

---Load Hoa don ban hang
GO
CREATE PROC HDBANHANG_Load
AS
BEGIN
	SELECT HDBH.MAHDBH ,NV.TENNV ,KH.TENKH ,HDBH.NGAYBH ,HDBH.THANHTIEN
	FROM (NHANVIEN NV join HDBANHANG HDBH on HDBH.MANV = NV.MANV) join KHACHHANG KH on HDBH.MAKH = KH.MAKH
END

---Load Hoa don theo MaKH
GO
CREATE PROC HDBANHANG_LoadKH(
	@MAKH char(5)
)
AS
BEGIN
	SELECT HDBH.MAHDBH ,NV.TENNV ,KH.TENKH ,HDBH.NGAYBH ,HDBH.THANHTIEN
	FROM (NHANVIEN NV join HDBANHANG HDBH on HDBH.MANV = NV.MANV) join KHACHHANG KH on HDBH.MAKH = KH.MAKH
	WHERE HDBH.MAKH = @MAKH
END
---Load Hoa don theo MaNV
GO
CREATE PROC HDBANHANG_LoadNV(
	@MANV char(5)
)
AS
BEGIN
	SELECT HDBH.MAHDBH ,NV.TENNV ,KH.TENKH ,HDBH.NGAYBH ,HDBH.THANHTIEN
	FROM (NHANVIEN NV join HDBANHANG HDBH on HDBH.MANV = NV.MANV) join KHACHHANG KH on HDBH.MAKH = KH.MAKH
	WHERE HDBH.MANV = @MANV
END
--- Loc hoa don theo ngay thang
GO
CREATE PROC HDBANHANG_Loc(
	@START SMALLDATETIME,
	@END SMALLDATETIME
)
AS
BEGIN
	SELECT HDBH.MAHDBH ,NV.TENNV ,KH.TENKH ,HDBH.NGAYBH ,HDBH.THANHTIEN
	FROM (NHANVIEN NV join HDBANHANG HDBH on HDBH.MANV = NV.MANV) join KHACHHANG KH on HDBH.MAKH = KH.MAKH
	WHERE HDBH.NGAYBH >= @START and HDBH.NGAYBH <= @END
END

---SP load search
GO
CREATE PROC SP_LoadSearch(
	@CHUOI NVARCHAR(50)
)
AS
BEGIN
	SELECT MASP, TENSP , DONGIA
	FROM SANPHAM
	WHERE FREETEXT(TENSP, @CHUOI) OR TENSP LIKE N'%' +@CHUOI+ '%'
END
--Xoa tai khoan khi xoa nhan vien
GO
CREATE PROC TKNhanVien_DeleteMaNV(
	@MANV CHAR(5)
)
AS
BEGIN
	DELETE 
	FROM TKNHANVIEN 
	WHERE MANV = @MANV
END

---Kiem tra san pham da co trong hoa don hay chua
GO
CREATE PROC CheckSPinHDBH(
	@MASP CHAR(5),
	@MAHDBH CHAR(5)
)
AS
BEGIN
	SELECT *
	FROM CTHDBANHANG 
	WHERE MASP = @MASP and MAHDBH= @MAHDBH
END

--- Update so luong trong cthdbh
GO 
CREATE PROC CTHDBanHang_UpdateSL(
	@MACTHDBH CHAR(5),
	@MASP CHAR(5),
	@SOLUONG INT
)
AS
BEGIN
	UPDATE CTHDBANHANG 
	SET 
		SOLUONG = @SOLUONG
	WHERE MACTHDBH = @MACTHDBH and MASP = @MASP
END

---tao view cho report
GO
Create view ViewDSSP
as
	select CTHDBH.MAHDBH, SP.MASP, SP.TENSP, CTHDBH.SOLUONG, SP.DONGIA, (CTHDBH.SOLUONG*SP.DONGIA) as THANHTIEN, SP.TGBAOHANH
	from (SANPHAM SP join CTHDBANHANG CTHDBH on SP.MASP = CTHDBH.MASP)

---tao hoa don ban hang
GO
CREATE PROC RPHDBH(
	@MAHDBH CHAR(5)
)
AS
BEGIN
	SELECT CTHDBH.MAHDBH, SP.MASP, SP.TENSP, CTHDBH.SOLUONG, SP.DONGIA, (CTHDBH.SOLUONG*SP.DONGIA) as THANHTIEN, SP.TGBAOHANH, KH.TENKH, KH.DIACHI, KH.SDT, HDBH.MAHDBH, HDBH.NGAYBH, NV.TENNV
	FROM (SANPHAM SP join CTHDBANHANG CTHDBH on SP.MASP = CTHDBH.MASP) join ((KHACHHANG KH join HDBANHANG HDBH on KH.MAKH = HDBH.MAKH) join NHANVIEN NV on HDBH.MANV = NV.MANV ) on CTHDBH.MAHDBH = HDBH.MAHDBH
	WHERE CTHDBH.MAHDBH = @MAHDBH
END

--- load thong tin khi in hoa don
GO
CREATE PROC RPTTHDBH(
	@MAHDBH CHAR(5)
)
AS
BEGIN
	SELECT KH.TENKH, KH.DIACHI, KH.SDT, HDBH.MAHDBH, HDBH.NGAYBH, NV.TENNV
	FROM (KHACHHANG KH join HDBANHANG HDBH on KH.MAKH = HDBH.MAKH) join NHANVIEN NV on HDBH.MANV = NV.MANV 
	WHERE HDBH.MAHDBH = @MAHDBH
END

---- thống kê hóa đơn theo date
GO
CREATE PROC FILTER_HDBH(
	@DATEBEGIN SMALLDATETIME,
	@DATEEND SMALLDATETIME
)
AS
BEGIN
	SELECT HDBH.MAHDBH, NV.TENNV, HDBH.NGAYBH, HDBH.THANHTIEN
	FROM HDBANHANG AS HDBH JOIN KHACHHANG AS KH ON HDBH.MAKH = KH.MAKH
	JOIN NHANVIEN AS NV ON HDBH.MANV = NV.MANV
	WHERE HDBH.NGAYBH >= @DATEBEGIN AND HDBH.NGAYBH <= @DATEEND
END

---- thống kê hóa đơn theo date
GO
CREATE PROC TEST
AS
BEGIN
	SELECT HDBH.MAHDBH, NV.TENNV, HDBH.NGAYBH, HDBH.THANHTIEN
	FROM HDBANHANG AS HDBH JOIN KHACHHANG AS KH ON HDBH.MAKH = KH.MAKH
	JOIN NHANVIEN AS NV ON HDBH.MANV = NV.MANV
END
---
GO
CREATE PROC [dbo].[HDNH_WITHMANCC]
( @MANCC CHAR(5)
)
AS
BEGIN
SELECT HDNH.MAHDNH, HDNH.MANV,NV.TENNV, HDNH.MANCC, NCC.TENNCC, HDNH.NGAYNH, HDNH.TONGTIEN
FROM HDNHAPHANG AS HDNH, NHANVIEN AS NV, NHACUNGCAP AS NCC
WHERE HDNH.MANV = NV.MANV AND HDNH.MANCC = NCC.MANCC AND HDNH.MANCC = @MANCC
END
GO
---
CREATE PROC [dbo].[HDNH_WITHMANV]
( @MANV CHAR(5)
)
AS
BEGIN
SELECT HDNH.MAHDNH, HDNH.MANV,NV.TENNV, HDNH.MANCC, NCC.TENNCC, HDNH.NGAYNH, HDNH.TONGTIEN
FROM HDNHAPHANG AS HDNH, NHANVIEN AS NV, NHACUNGCAP AS NCC
WHERE HDNH.MANV = NV.MANV AND HDNH.MANCC = NCC.MANCC AND HDNH.MANV = @MANV
END
GO
---
CREATE PROC	[dbo].[HDNhapHang_Load_Day](
@DAYBEGIN SMALLDATETIME,
@DAYEND	SMALLDATETIME
)
AS
BEGIN
SELECT HDNH.MAHDNH, HDNH.MANV,NV.TENNV, HDNH.MANCC, NCC.TENNCC, HDNH.NGAYNH, HDNH.TONGTIEN
FROM HDNHAPHANG AS HDNH, NHANVIEN AS NV, NHACUNGCAP AS NCC
WHERE HDNH.MANV = NV.MANV AND HDNH.MANCC = NCC.MANCC AND 
NGAYNH >= @DAYBEGIN AND
NGAYNH <= @DAYEND	
END
GO
--- update Tong thanh tien HDNH ---
CREATE PROC UP_HDNH_THANHTOAN(
@TONGTIEN INT,
@MAHDNH CHAR(5)
)
AS 
BEGIN
UPDATE HDNHAPHANG
SET TONGTIEN = @TONGTIEN
WHERE MAHDNH = @MAHDNH
END
GO