--- Lấy tất cả nhà cung cấp ra.
CREATE PROC NhaCungCap_SelectAll
AS
BEGIN
	SELECT * FROM NHACUNGCAP 
END

--- Lấy tất cả hóa đươn nhập hàng ra
GO
CREATE PROC HoaDonNhap_SelectAll
AS
BEGIN 
	SELECT * FROM HDNHAPHANG
END

--- Load MAHDNH, TENNV, TENNCC, NGAYNH, TONGTIEN
GO
CREATE PROC HoaDonNhap_Load
AS
BEGIN 
	SELECT HDNH.MAHDNH, HDNH.MANV,NV.TENNV, HDNH.MANCC, NCC.TENNCC, HDNH.NGAYNH, HDNH.TONGTIEN
	FROM HDNHAPHANG AS HDNH, NHANVIEN AS NV, NHACUNGCAP AS NCC
	WHERE HDNH.MANV = NV.MANV AND HDNH.MANCC = NCC.MANCC
END

--- Insert hóa đơn nhập
GO
CREATE PROC HoaDonNhap_Insert(
	@MAHDNH CHAR(5),
	@MANV CHAR(5),
	@MANCC CHAR(5),
	@NGAYNH SMALLDATETIME,
	@TONGTIEN MONEY
)
AS
BEGIN
	INSERT INTO HDNHAPHANG(MAHDNH, MANV, MANCC, NGAYNH, TONGTIEN) 
	VALUES (@MAHDNH, @MANV, @MANCC, @NGAYNH, @TONGTIEN)
END
GO
--- Delete hóa đơn nhập
GO
CREATE PROC HoaDonNhap_Delete(
	@MAHDNH CHAR(5)
)
AS
BEGIN
	DELETE FROM CTHDNHAPHANG WHERE MAHDNH = @MAHDNH
	DELETE FROM HDNHAPHANG WHERE MAHDNH = @MAHDNH
END


--- Load chi tiết hóa đơn nhập
GO
CREATE PROC CTHDNhap_Load(
	@MAHDNH CHAR(5)
)
AS
BEGIN
	SELECT CTHDNH.MACTHDNH, CTHDNH.MAHDNH,CTHDNH.MASP, SP.TENSP, CTHDNH.SOLUONG, CTHDNH.GIANHAP 
	FROM SANPHAM AS SP, CTHDNHAPHANG AS CTHDNH
	WHERE CTHDNH.MASP = SP.MASP AND CTHDNH.MAHDNH = @MAHDNH
END

--- Thêm chi tiết hóa đơn nhập
GO
CREATE PROC CTHDNhap_Insert(
	@MACTHDNH CHAR(5),
	@MAHDNH CHAR(5),
	@MASP CHAR(5),
	@SOLUONG INT,
	@GIANHAP MONEY
)
AS
BEGIN
	INSERT INTO CTHDNHAPHANG(MACTHDNH, MAHDNH, MASP, SOLUONG, GIANHAP) 
	VALUES (@MACTHDNH, @MAHDNH, @MASP, @SOLUONG, @GIANHAP)
END
GO

--- Lấy Mã nhân viên, Tên nhân viên
CREATE PROC NhanVien_Select_Element
AS
BEGIN
	SELECT MANV, TENNV
	FROM NHANVIEN
END
GO

--- Lay danh sach NCC theo 
CREATE PROC NhaCungCap_Select_Element
AS
BEGIN
	SELECT MANCC, TENNCC
	FROM NHACUNGCAP
END
GO


--- Delete chi tiết hóa đơn nhập
CREATE PROC CTHDNhap_Delete(
	@MACTHDNH CHAR(5)
)
AS
BEGIN
	DELETE FROM CTHDNHAPHANG WHERE MACTHDNH = @MACTHDNH
END
GO
--- DELETE CI HDNHAP 
CREATE PROC CTHDNhap_Delete_NOMACT(
	@MAHDNH CHAR(5),
	@MASP CHAR(5)
)
AS
BEGIN
	DELETE FROM CTHDNHAPHANG WHERE MAHDNH = @MAHDNH AND MASP = @MASP
END
GO
--- SEARCH 
--- UPADATE HD NHAP HANG
CREATE PROC HDNhapHang_Update(
	@MAHDNH CHAR(5),
	@MANV CHAR(5),
	@MANCC CHAR(5),
	@NGAYNHAP DATETIME,
	@TONGTT MONEY
)
AS
BEGIN
	UPDATE HDNHAPHANG
	SET MANV = @MANV, MANCC = @MANCC, NGAYNH= @NGAYNHAP, TONGTIEN = @TONGTT
	WHERE MAHDNH = @MAHDNH
END
GO
--- UPDATE CTHD NHAP HANG ---
CREATE PROC CTHD_Update2(
	@MACTHDN CHAR(5),
	@MAHDNH CHAR(5),
	@MASP CHAR(5),
	@SOLUONG INT,
	@GIANHAP MONEY
)
AS
BEGIN
	UPDATE CTHDNHAPHANG
	SET MACTHDNH = @MACTHDN, MAHDNH = @MAHDNH, MASP= @MASP, SOLUONG= @SOLUONG, GIANHAP = @GIANHAP
	WHERE MAHDNH = @MAHDNH AND MASP = @MASP
END
GO
--- LAY MA HDNHAP LON NHAT ---
CREATE PROC HDN_MAHDN_TOP1
AS
BEGIN
	SELECT TOP 1 MAHDNH
	FROM HDNHAPHANG
	ORDER BY MAHDNH DESC
END
GO
--- --- LAY MA CTHDNHAP LON NHAT ---
CREATE PROC HDN_CTHDN_TOP1
AS
BEGIN
	SELECT TOP 1 MACTHDNH
	FROM CTHDNHAPHANG
	ORDER BY MACTHDNH DESC
END
GO

--- LOAD SP ---
CREATE PROC LOAD_SANPHAM_ELEMENT
AS
BEGIN
	SELECT MASP, TENSP
	FROM SANPHAM
END
GO
--- HOADONNHAPHANG _ WITH MAHD ---
CREATE PROC HDNH_WITHMAHD
( @MAHDNH CHAR(5)
)
AS
BEGIN
	SELECT HDNH.MAHDNH, HDNH.MANV,NV.TENNV, HDNH.MANCC, NCC.TENNCC, HDNH.NGAYNH, HDNH.TONGTIEN
	FROM HDNHAPHANG AS HDNH, NHANVIEN AS NV, NHACUNGCAP AS NCC
	WHERE HDNH.MANV = NV.MANV AND HDNH.MANCC = NCC.MANCC AND MAHDNH = @MAHDNH
END
GO