--- Load Nhân viên
CREATE PROC	Nhanvien_Load
AS
BEGIN
	SELECT * FROM NHANVIEN
END

---Thêm nhân viên
GO
CREATE PROC	Nhanvien_Insert(
	@MANV CHAR(5),
	@TENNV NVARCHAR(5),
	@NGSINH SMALLDATETIME,
	@GIOITINH NVARCHAR(3),
	@DIACHI NVARCHAR(50),
	@SDT VARCHAR(11),
	@MALOAI CHAR(5)
)
AS
BEGIN
	INSERT INTO NHANVIEN VALUES (@MANV, @TENNV, @NGSINH, @GIOITINH, @DIACHI, @SDT, @MALOAI)
END

---Xóa nhân viên
GO
CREATE PROC	Nhanvien_Detele(
	@MANV CHAR(5)
)
AS
BEGIN
	DELETE FROM NHANVIEN WHERE MANV = @MANV
END

---Sửa nhân viên
GO
CREATE PROC	Nhanvien_Update(
	@MANV CHAR(5),
	@TENNV NVARCHAR(5),
	@NGSINH SMALLDATETIME,
	@GIOITINH NVARCHAR(3),
	@DIACHI NVARCHAR(50),
	@SDT VARCHAR(11),
	@MALOAI CHAR(5)
)
AS
BEGIN
	UPDATE NHANVIEN 
	SET TENNV = @TENNV, 
		NGSINH = @NGSINH, 
		GIOITINH = @GIOITINH, 
		DIACHI = @DIACHI,
		SDT = @SDT,
		MALOAI = @MANV
	WHERE MANV = @MANV
END